[asumono_krom]
flag = "ğŸ‡®ğŸ‡©"
avatar = "asumono_krom@twitter"
name = "Joseph A.K"
alias = ["choroi_dragon", "asumonokrom", "joseph"]
socials = [
    { code = "x", name = "asumono_krom", desc = "JOSEPH A.K" },
    { code = "x", name = "Choroi_dragon", desc = "ChoroGon! ğŸ”" },
    { code = "bsky", name = "asumonokrom.bsky.social" },
    { code = "instagram", name = "anjing_kampus" },
]

[basch]
flag = "ğŸ‡¦ğŸ‡·"
avatar = "BaschIsTaken@twitter"
name = "Basch"
alias = ["baschistaken"]
socials = [
    { code = "x", name = "BaschIsTaken" },
    { code = "fa", name = "basch" },
    { code = "picarto", name = "basch" },
    { code = "patreon", name = "BaschWasTaken" },
]

[caronte]
flag = "ğŸ‡ªğŸ‡¸"
avatar = "MightyChorizo@twitter"
name = "Caronte"
alias = ["caronte_cafe", "mightychorizo", "carontearts", "car0nte"]
socials = [
    { code = "_", desc = "caronte.cafe", link = "https://caronte.cafe/" },
    { code = "x", name = "MightyChorizo" },
    { code = "fa", name = "car0nte" },
    { code = "bsky", name = "caronte.cafe" },
    { code = "telegram", name = "+DICDyfABQOkyNjk0" },
]

[cass_ito]
avatar = "lewd_bunnie@twitter"
alias = ["cassito", "mrcass", "lewd_bunnie"]
socials = [
    { code = "x", name = "Lewd_bunnie" },
    { code = "x", name = "cass_ito", desc = "Alt" },
    { code = "twitter", name = "cassitochannel18" },
    { code = "kofi", name = "cass_notgay" },
]

[drboumboom]
avatar = "DrBoom32@twitter"
name = "DrBoumBoom32"
alias = ["drboom32", "drboumboom32"]
socials = [
    { code = "x", name = "DrBoom32" },
    { code = "patreon", name = "drboumboom32" },
]

[kamyuel]
flag = "ğŸ‡°ğŸ‡·"
avatar = "kamyuelo@twitter"
name = "Kamyuel"
alias = ["kamyuelo"]
socials = [
    { code = "x", name = "Kamyuelo" },
    { code = "fa", name = "kamyuel" },
    { code = "patreon", name = "kamyuel" },
    { code = "gumroad", name = "kamyuel" },
]

[kurogon]
flag = "ğŸ‡¯ğŸ‡µ"
name = "Kurogon"
alias = ["kurogon0227", "kuroma"]
socials = [
    { code = "twitter", name = "kurogon0227" },
    { code = "pixiv", name = "kurogon0227" },
    { code = "fa", name = "kuroma" },
    { code = "picarto", name = "kurogon" },
]

[memburu]
avatar = "https://a.furaffinity.net/1643969840/memburu.gif"
name = "Memburu"
socials = [
    { code = "patreon", name = "memburu" },
    { code = "fa", name = "memburu" },
]

[nomifuki]
flag = "ğŸ‡¯ğŸ‡µ"
avatar = "nomifuki@twitter"
socials = [
    { code = "x", name = "nomifuki" },
    { code = "x", name = "nomifuki2", desc = "SFW" },
    { code = "booth", name = "nomifuki" },
    { code = "patreon", name = "nomifuki" },
    { code = "fanbox", name = "nomifuki" },
]

[noswift]
avatar = "No_SWIFT@twitter"
name = "NoSWIFT"
alias = ["no_swift"]
socials = [
    { code = "_", desc = "noswift.art", link = "https://noswift.art/" },
    { code = "bsky", name = "noswift.art" },
    { code = "fa", name = "noswift" },
    { code = "x", name = "No_SWIFT" },
    { code = "telegram", name = "+-P7fIIyqCWowNGYx" },
    { code = "patreon", name = "NoSWIFT" },
    { code = "kofi", name = "noswift" },
]

[nullghost]
avatar = "NullGhost_Art@twitter"
name = "Null-Ghost"
alias = ["null-ghost", "nullghostart"]
socials = [
    { code = "twitter", name = "NullGhostArt" },
    { code = "twitter", name = "NullGhost_Art", desc = "Alt" },
    { code = "bsky", name = "nullghostart.bsky.social" },
    { code = "telegram", name = "NullGhostArt" },
    { code = "patreon", name = "NullGhostArt" },
    { code = "gumroad", name = "nullghost" },
]

[raccoon21]
flag = "ğŸ‡°ğŸ‡·"
name = "Raccoon21"
alias = ["raccoon21c", "21c-raccoon", "21centuryraccoon"]
socials = [
    { code = "_", desc = "Raccoon21C Comic", link = "https://www.21craccooncomic.com/" },
    { code = "twitter", name = "Raccoon_21C" },
    { code = "bsky", name = "raccoon21c.bsky.social" },
    { code = "itaku", name = "21c-Raccoon" },
    { code = "patreon", name = "21CenturyRaccoon" },
    { code = "gumroad", name = "21centuryraccoon" },
]

[ralefov]
flag = "ğŸ‡»ğŸ‡³"
avatar = "Ralefov@twitter"
name = "Ralefov"
alias = ["rale"]
socials = [
    { code = "linktree", name = "ssssnowy" },
    { code = "x", name = "SSSsnowyartist" },
]

[ssssnowy]
flag = "ğŸ‡®ğŸ‡¹"
avatar = "SSSsnowyartist@twitter"
name = "SSSsnowy"
alias = ["snowby", "snowy"]
socials = [{ code = "x", name = "Ralefov" }, { code = "fa", name = "ralefov" }]

[tokuni]
flag = "ğŸ‡¯ğŸ‡µ"
avatar = "toktoktokuni@twitter"
name = "ğ“ğ¨ğ¤ğ®ğ§ğ¢"
alias = ["toktoktokuni", "tokuni-naihito"]
socials = [
    { code = "x", name = "toktoktokuni" },
    { code = "pixiv", name = "98281842" },
    { code = "booth", name = "tokuni-naihito" },
    { code = "skeb", name = "vLW4zegrsGtSI6e" },
]
